---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - local-queue.yaml
  - sample-pipelineruns-aws-amd64.yaml
namespace: pipelinerun-may-tenant-dynamic
