---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - may.konflux-ci.dev
  resources:
  - dynamichosts
  - statichosts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - may.konflux-ci.dev
  resources:
  - dynamichosts/finalizers
  - statichosts/finalizers
  verbs:
  - update
- apiGroups:
  - may.konflux-ci.dev
  resources:
  - dynamichosts/status
  - statichosts/status
  verbs:
  - get
  - patch
  - update
