name: Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  merge_group:
    types: [checks_requested]

jobs:
  test:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    # for OIDC authentication with Codecov
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        component:
        - "drivers/incluster"
        - "drivers/aws"
        - "drivers/ibm"
        - "may"

    defaults:
      run:
        working-directory: "./${{ matrix.component }}"

    steps:
      - name: Clone the code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Setup Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: "${{ matrix.component }}/go.mod"

      - name: Running Tests coverage
        run: |
          go mod tidy
          make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5
        with:
          use_oidc: true
          flags: unit-tests
          files: ${{ matrix.component }}/cover.out
          fail_ci_if_error: false
