name: Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    # for OIDC authentication with Codecov
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        component:
        - "drivers/incluster"
        - "drivers/aws"
        - "drivers/ibm"
        - "may"

    defaults:
      run:
        working-directory: "./${{ matrix.component }}"

    steps:
      - name: Clone the code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: "${{ matrix.component }}/go.mod"

      - name: Running Tests coverage
        run: |
          go mod tidy
          make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          flags: unit-tests
          files: ${{ matrix.component }}/cover.out
          fail_ci_if_error: false